version: "3.8"

services:
  lb:
    image: lb:latest
    build:
      context: ./infra/nginx
    ports:
      - 80:80
    networks:
      - cocktail-app
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - cocktail-app
  s3:
    image: minio/minio
    container_name: s3
    restart: unless-stopped
    volumes:
      - ./data/minio_storage:/data
      - ./tmp:/var/log/nginx/
    environment:
      MINIO_ROOT_USER: s3user
      MINIO_ROOT_PASSWORD: s3password
    ports:
      - "9000:9000"
      - "9090:9090"
    command: minio server /data --console-address ":9090"
    networks:
      - cocktail-app
  api:
    image: api:latest
    build:
      context: ./
      dockerfile: Dockerfile.api

    environment:
      DB_HOST: db
      S3_URL: http://s3:9000
      S3_BUCKET: cocktail-pictures
      S3_ACCESS_KEY: TtJnQSJ9SadIZZ1e
      S3_SECRET_KEY: XWKAakdVyPv0YrHI0AAcP5JfaqGk1rGS
    ports:
      - 3000:3000
    networks:
      - cocktail-app
  front:
    image: front:latest
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - 4173:80
    networks:
      - cocktail-app

networks:
  cocktail-app:
    name: cocktail-app
