version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - cocktail-app

  s3:
    image: minio/minio
    container_name: s3
    restart: unless-stopped
    volumes:
      - ./data/minio_storage:/data
    environment:
      MINIO_ROOT_USER: s3user
      MINIO_ROOT_PASSWORD: s3password
    ports:
      - "9000:9000"
      - "9090:9090"
    command: minio server /data --console-address ":9090"
  api:
    image: cocktails-app-api:tmp
    build:
      context: ./
      dockerfile: Dockerfile.api

    environment:
      DB_HOST: db
    ports:
      - 3000:3000
    networks:
      - cocktail-app

networks:
  cocktail-app:
    name: cocktail-app
