version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - cocktail-app

networks:
  cocktail-app:
    name: cocktail-app
